export const projectsList: ProjectModel[] = [
  {
    id: '1',
    name: 'Exam Samaya',
    description: 'E learning platform for students of engineering and medical to prepare for their license examination in nepal.',
    thumbnail: 'https://alkyhora.sirv.com/portfolio/exam_samaya_cover.png',
    logo: 'https://alkyhora.sirv.com/portfolio/logo.png',
    liveLink: 'https://examsamaya.com/',
    detailLink: '#',
    journey: {
      scopes: ["mobile", "web app"],
      status: "live",
    },
  },
  {
    id: '2',
    name: 'Bodh News Application',
    description: 'News application for people in nepal to get latest news and updates with political biases.',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
    liveLink: null,
    logo: 'https://alkyhora.sirv.com/portfolio/talewears_logo.png',
    detailLink: '#',
    journey: {
      scopes: ["mobile", "web app"],
      status: "ongoing",
    },
  },
  {
    id: '3',
    name: 'Talewears',
    description: 'E commerce site for selling anything related to clothing and fashion.',
    thumbnail: 'https://alkyhora.sirv.com/portfolio/talewears-cover.png',
    liveLink: null,
    logo: 'https://alkyhora.sirv.com/portfolio/talewears_logo.png',
    detailLink: '#',
    journey: {
      scopes: ["web"],
      status: "ongoing",
    },
  },
  {
    id: '4',
    name: 'HISSAN Exam management system',
    description: 'Exam management system for HISSAN Kaski, digitalizing the examination process for schools and colleges.',
    thumbnail: 'https://alkyhora.sirv.com/portfolio/b.png',
    liveLink: null,
    logo: 'https://alkyhora.sirv.com/portfolio/talewears_logo.png',
    detailLink: '#',
    journey: {
      scopes: ["web app"],
      status: "ongoing",
    },
  },
  {
    id: '5',
    name: 'Ghar Phela',
    description: 'Real estate platform for buying and selling properties in nepal.',
    thumbnail: 'https://alkyhora.sirv.com/portfolio/gharphela_cover.png',
    liveLink: 'https://gharphela.netlify.app/',
    detailLink: '#',
    logo: 'https://alkyhora.sirv.com/portfolio/gharphela_logo.png',
    journey: {
      scopes: ["web"],
      status: "live",
    },
  },
];