export const projectsList: (ProjectModel & { colSpan: number })[] = [
  {
    id: '1',
    name: 'Exam Samaya',
    description: 'E learning platform for students of engineering and medical to prepare for their license examination in nepal.',
    thumbnail: 'https://alkyhora.sirv.com/portfolio/exam_samaya_cover.png',
    logo: 'https://alkyhora.sirv.com/portfolio/logo.png',
    liveLink: 'https://examsamaya.com/',
    detailLink: '#',
    journey: {
      scopes: ["mobile", "web app"],
      status: "live",
    },
    colSpan: 3,
  },
  {
    id: '2',
    name: 'Bodh News Application',
    description: 'News application for people in nepal to get latest news and updates with political biases.',
    thumbnail: 'https://alkyhora.sirv.com/portfolio/bodh-news.png',
    liveLink: null,
    logo: 'https://alkyhora.sirv.com/portfolio/talewears_logo.png',
    detailLink: '#',
    journey: {
      scopes: ["mobile", "web app"],
      status: "ongoing",
    },
    colSpan: 1,
  },
  {
    id: '3',
    name: 'Talewears',
    description: 'E commerce site for selling anything related to clothing and fashion.',
    thumbnail: 'https://alkyhora.sirv.com/portfolio/talewears-cover.png',
    liveLink: null,
    logo: 'https://alkyhora.sirv.com/portfolio/talewears_logo.png',
    detailLink: '#',
    journey: {
      scopes: ["web"],
      status: "ongoing",
    },
    colSpan: 2,
  },
  {
    id: '4',
    name: 'Ghar Phela',
    description: 'Real estate platform for buying and selling properties in nepal.',
    thumbnail: 'https://alkyhora.sirv.com/portfolio/gharphela_cover.png',
    liveLink: 'https://gharphela.netlify.app/',
    detailLink: '#',
    logo: 'https://alkyhora.sirv.com/portfolio/gharphela_logo.png',
    journey: {
      scopes: ["web"],
      status: "live",
    },
    colSpan: 2,
  },
  {
    id: '5',
    name: 'HISSAN Exam management system',
    description: 'Exam management system for HISSAN Kaski, digitalizing the examination process for schools and colleges.',
    thumbnail: 'https://alkyhora.sirv.com/portfolio/b.png',
    liveLink: null,
    logo: 'https://alkyhora.sirv.com/portfolio/talewears_logo.png',
    detailLink: '#',
    journey: {
      scopes: ["web app"],
      status: "ongoing",
    },
    colSpan: 1,
  },
];