export const teams: Team = {
  coreTeams: [
    {
      id: 0,
      name: "Alson Garbuja",
      position: "Co-Founder & Full Stack Developer",
      image: "/images/alson.png",
      linkedin: "https://www.linkedin.com/in/alsongarbuja/",
      github: "https://github.com/alsongarbuja",
      portfolio: "https://alsongarbuja.com.np",
    },
    {
      id: 1,
      name: "Bipin Adhikari",
      position: "Co-Founder & App Developer",
      image: "/images/bipin.png",
      linkedin: "https://linkedin.com/in/bipinad",
      github: "https//github.com/bipinad",
      portfolio: null,
    },
    {
      id: 2,
      name: "Sunil Paudel",
      position: "Co-Founder & Frontend Developer",
      image: "/images/sunil.png",
      linkedin: "https://linkedin.com/in/sunil-paudel-482a4125a",
      github: "https://github.com/SunilPdl",
      portfolio: null,
    },
    {
      id: 3,
      name: "Susant Basnet",
      position: "Co-Founder & Frontend Developer",
      image: "https://media.licdn.com/dms/image/D4D03AQGqQSGAyIDh-g/profile-displayphoto-shrink_800_800/0/1688698869409?e=2147483647&v=beta&t=7-1xQPFJ3qvKI2KcWm-wMXJIey76SV9alAulN-idxkk",
      linkedin: "https://linkedin.com/in/susant-basnet-79b185254",
      github: "https://github.com/Susant-Basnet",
      portfolio: null,
    },
    {
      id: 4,
      name: "Utsab Gurung",
      position: "Co-Founder & Frontend Developer",
      image: "/images/utsab.png",
      linkedin: "https://linkedin.com/in/utsab-gurung-928b0b280",
      github: "https://github.com/utsab043",
      portfolio: null,
    },
  ],
  developers: [
    {
      id: 0,
      name: "Prasiddha Khadka",
      position: "App Developer",
      image: "https://avatars.githubusercontent.com/u/53443661?v=4",
      linkedin: "https://www.linkedin.com/in/prasiddha-khadka/",
      github: "https://github.com/Prasiddha777",
      portfolio: null,
    },
  ],
  designers: [],
  marketers: [],
  testers: [],
  others: [],
}